name: 🌱 Feature Request
description: Request a new feature or enhancement.
title: "[FEAT]:"
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for the Mautic User Documentation! Please fill out the details below to help us understand and prioritize it.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the feature you would like to see.
      placeholder: "e.g., I'd like to be able to edit the documentation directly on GitHub. This would be useful because..."
    validations:
      required: true

  - type: dropdown
    id: willingness-to-pr
    attributes:
      label: Are you willing to help us add this feature this by making a pull request?
      description: Contributing a pull request is the fastest way to get this fixed.
      options:
        - "— Select an option —"
        - "No"
        - "Yes"
        - "Yes, but I need help"
    validations:
      required: true
  
  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions (Optional)
      description: How do you suggest this feature should be implemented?
      placeholder: "e.g., A user could click the edit button on the documentation page to make changes."