name: 🐛 Technical Bug Report
description: Did you find a bug with the documentation system or automations? Create a report to help us improve.
title: "[BUG]:"
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a technical bug within the Mautic User Documentation! Please fill out the details below to help us understand and resolve it.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the bug. Include steps to reproduce the behavior, the expected result, and the actual result.
      placeholder: "e.g., Running make html command didn't build the docs. Steps to reproduce: 1. Go to the /docs directory. 2. Run make html command. 3. Nothing happens."
    validations:
      required: true

  - type: dropdown
    id: willingness-to-pr
    attributes:
      label: Are you willing to help us fix this by making a pull request?
      description: Contributing a pull request is the fastest way to get this fixed.
      options:
        - "— Select an option —"
        - "No"
        - "Yes"
        - "Yes, but I need help"
    validations:
      required: true

  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions (Optional)
      description: How do you suggest this bug could be fixed?
      placeholder: "e.g., I think changing X to Y would solve the issue."
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment where the bug occurred.
        - OS/Platform
        - Browser & Version
      placeholder: "e.g., Windows 11, Chrome v125"
  
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Screen Recordings (Optional)
      description: To help us understand the issue visually, please attach any relevant images or recordings.
      placeholder: "Drag and drop the files here."