contact_links:
  - name: Mautic Community Support
    url: https://forum.mautic.org/
    about: Please ask questions around Mautic product here.
  - name: Report a bug for the Mautic product
    url: https://github.com/mautic/mautic/issues
    about: Please create an issue to report a bug in the Mautic product here.